### ISSUE TITLE
Example Playbook for 1 node master and 1 node slave

### ISSUE THREAD

**Issue by manuparra** [grycap/ansible-role-hadoop#12]
Hello ¿ could you write a simple example to create a playbook for 1 master and 1 node (sharing datanode, resourcenode, etc), in order to check if your ansible role works? Without ansible-galaxy? 

```
- hosts: hadoop_namenode
   become: yes
   vars:
       namenode_ip: 192.168.10.10
       datanode_ip: 192.168.10.10
       version: '2.8.0'
   roles:
      { role: 'grycap.hadoop', hadoop_master: '{{namenode_ip}}', hadoop_type_of_node: 'master', hadoop_version: '{{version}}' }
      { role: 'grycap.hadoop', hadoop_master: '{{datanode_ip}}', hadoop_version: '{{version}}' }
```
Regards.
